version: "3.7"
services:
  docker-nginx:
    image: docker-nginx
    hostname: docker-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: docker-nginx
    ports:
      - 80:80
    volumes:
      - ./www:/srv/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
  docker-phpfpm:
    image: docker-phpfpm
    hostname: docker-phpfpm
    build:
      context: ./phpfpm
      dockerfile: Dockerfile
    container_name: docker-phpfpm
    volumes:
      - ./www:/srv/www
    networks:
      - www
networks:
  www:
